version: '3'

services:
  backend:
    image: node:18
    volumes:
      - ./backend:/backend
    command: bash -c "cd /backend && npm install && npm run dev"
    expose:
      - 3000
  frontend:
    image: node:18
    volumes:
      - ./frontend:/frontend
    command: bash -c "cd /frontend && npm install && npm run dev"
    ports:
      - 8080:3000
    depends_on:
      - backend
